### ISSUE TITLE
Gramine failing to run latest version of nodejs 20.9.0

### ISSUE THREAD

**Issue by jinengandhi-intel** [gramineproject/examples#83] opened 2023-11-21 07:47 UTC
Nodejs 20.x fails when run with Gramine Direct and Gramine SGX 

Logs for both are attached.
[graminesgx_error_nodejs_version_20.txt](https://github.com/gramineproject/examples/files/13423179/graminesgx_error_nodejs_version_20.txt)
[graminedirect_error_nodejs_version_20.txt](https://github.com/gramineproject/examples/files/13423181/graminedirect_error_nodejs_version_20.txt)

**Comment by jinengandhi-intel** [comment] 2023-11-21 08:24
I didn't realize this was already known, as this version is only now pushed for Alpine distro, so our Nightly runs only caught this now.

**Comment by jinengandhi-intel** [comment] 2023-11-21 12:44
@kailun-qin Like you said, I quickly checked on ubuntu20.04 also and there too apt installs a much older version i.e. 10.19 where the issue is not seen. I followed the steps listed [here ](https://deb.nodesource.com/) to upgrade to 20.x and I see the issue there. 

Updating the title and description to remove references to Alpine.

**Comment by mkow** [comment] 2023-11-21 13:50
Closing, as it's a duplicate of https://github.com/gramineproject/gramine/issues/1469.

**Closed by mkow** 2023-11-21 13:50 UTC
